import type { Case } from '../types/case';

export const mockCases: Case[] = [
  {
    id: 'case-001',
    caseNumber: 'UK-PAURI-2026-00192',
    projectTitle: 'Rishikesh–Karanprayag Broad Gauge Rail Link Project (Tunnels & Approach Track)',
    projectPurpose: 'Strategic national railway infrastructure connectivity under Ministry of Railways',
    requiringDepartment: 'Rail Vikas Nigam Limited (RVNL)',
    state: 'Uttarakhand',
    district: 'Pauri Garhwal',
    tehsil: 'Srinagar',
    mauza: 'Rampur',
    khasraNumbers: ['442/19-A', '442/19-B', '445/02', '448/11-C'],
    stage: 'STAGE_4_SEC11_NOTIFICATION',
    stageNumber: 4,
    totalAreaHectares: 34.25,
    affectedFamiliesCount: 86,
    totalEstimatedCompensation: 184500000,
    disbursedCompensation: 62000000,
    dateInitiated: '2025-11-14',
    lastUpdated: '2026-08-28',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 11(1) Preliminary Gazette Notification',
    parcels: [
      { khasraNumber: '442/19-A', mauza: 'Rampur', soilType: 'Terraced Irrigated (Talaon)', areaHectares: 12.4, ownerName: 'Surendra Singh Rawat', circleRatePerSqMtr: 1450, solatiumMultiplier: 2.0 },
      { khasraNumber: '442/19-B', mauza: 'Rampur', soilType: 'Non-irrigated (Upraon)', areaHectares: 8.1, ownerName: 'Govind Ram Bhatt', circleRatePerSqMtr: 950, solatiumMultiplier: 2.0 },
      { khasraNumber: '445/02', mauza: 'Rampur', soilType: 'Settlement Residential', areaHectares: 4.75, ownerName: 'Kamala Devi Negi', circleRatePerSqMtr: 2800, solatiumMultiplier: 2.0 },
      { khasraNumber: '448/11-C', mauza: 'Rampur', soilType: 'Pasture / Barren', areaHectares: 9.0, ownerName: 'Gram Sabha Rampur', circleRatePerSqMtr: 600, solatiumMultiplier: 2.0 }
    ],
    auditTrail: [
      {
        id: 'aud-001',
        timestamp: '2025-11-14T10:30:00Z',
        actorName: 'Deepak Sharma, Chief Project Manager',
        actorRole: 'REQUIRING_BODY',
        action: 'SUBMIT_PROPOSAL',
        stage: 'STAGE_1_PROPOSAL_PENDING',
        details: 'Initial Land Acquisition Proposal Form-1 submitted with alignment map & Khasra schedule.',
        sha256Hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
      },
      {
        id: 'aud-002',
        timestamp: '2025-12-05T14:15:00Z',
        actorName: 'Ashish Joshi, IAS (District Collector)',
        actorRole: 'COLLECTOR',
        action: 'APPROVE_FORWARD',
        stage: 'STAGE_2_COLLECTOR_SCRUTINY',
        details: 'Verified cadastral boundaries,Mauza survey records, and forwarded proposal to State SIA Directorate.',
        sha256Hash: 'c4ca4238a0b923820dcc509a6f75849b2efb459461f893114a4282c0602f37c3'
      },
      {
        id: 'aud-003',
        timestamp: '2026-03-20T11:00:00Z',
        actorName: 'Dr. Meenakshi Sundaram (SIA Chairman)',
        actorRole: 'SIA_EXPERT',
        action: 'SUBMIT_SIA_VERDICT',
        stage: 'STAGE_3_SIA_EVALUATION',
        details: 'Social Impact Assessment public hearings held in Mauza Rampur. Positive recommendation with mitigation package.',
        sha256Hash: '8b1a9953c4611296a827abf8c47804d74542d99d14fcbe8a096c41b8a531b40c'
      },
      {
        id: 'aud-004',
        timestamp: '2026-08-28T09:45:00Z',
        actorName: 'Ashish Joshi, IAS (District Collector)',
        actorRole: 'COLLECTOR',
        action: 'PUBLISH_GAZETTE_SEC11',
        stage: 'STAGE_4_SEC11_NOTIFICATION',
        details: 'Gazette Notification No. UK/DL/2026/049 issued under Section 11(1). 60-day window opened for Section 15 objections.',
        sha256Hash: 'd4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35'
      }
    ]
  },
  {
    id: 'case-002',
    caseNumber: 'MH-THN-2026-00814',
    projectTitle: 'Mumbai–Ahmedabad High Speed Rail (MAHSR Bullet Train) Thane Feeder Corridor',
    projectPurpose: 'High speed rail terminal and electric traction substation construction',
    requiringDepartment: 'National High Speed Rail Corporation Limited (NHSRCL)',
    state: 'Maharashtra',
    district: 'Thane',
    tehsil: 'Bhiwandi',
    mauza: 'Anjur',
    khasraNumbers: ['108/3', '109/1', '112/4-A'],
    stage: 'STAGE_5_OBJECTIONS_HEARING',
    stageNumber: 5,
    totalAreaHectares: 18.9,
    affectedFamiliesCount: 52,
    totalEstimatedCompensation: 320000000,
    disbursedCompensation: 0,
    dateInitiated: '2025-09-02',
    lastUpdated: '2026-09-01',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 15 Objections & Landowner Hearings',
    parcels: [
      { khasraNumber: '108/3', mauza: 'Anjur', soilType: 'Agri-Commercial', areaHectares: 7.2, ownerName: 'Rajesh Vitthal Patil', circleRatePerSqMtr: 4200, solatiumMultiplier: 2.0 },
      { khasraNumber: '109/1', mauza: 'Anjur', soilType: 'Non-Agricultural Land', areaHectares: 5.5, ownerName: 'Bhiwandi Warehousing Corp', circleRatePerSqMtr: 5800, solatiumMultiplier: 2.0 },
      { khasraNumber: '112/4-A', mauza: 'Anjur', soilType: 'Agricultural Irrigated', areaHectares: 6.2, ownerName: 'Pandurang Mhatre & 4 Others', circleRatePerSqMtr: 3900, solatiumMultiplier: 2.0 }
    ],
    auditTrail: [
      {
        id: 'aud-005',
        timestamp: '2026-09-01T16:20:00Z',
        actorName: 'Prakash Surve, Dy. Collector (Land Acquisition)',
        actorRole: 'COLLECTOR',
        action: 'LOG_OBJECTION',
        stage: 'STAGE_5_OBJECTIONS_HEARING',
        details: 'Section 15 objection #OBJ-014 logged regarding structure valuation on Khasra 109/1.',
        sha256Hash: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a'
      }
    ]
  },
  {
    id: 'case-003',
    caseNumber: 'UP-NOIDA-2026-00045',
    projectTitle: 'Noida International Airport Jewar (Phase 2 Multi-Modal Logistics Hub)',
    projectPurpose: 'Cargo terminal, runway expansion, and peripheral surface transportation network',
    requiringDepartment: 'Yamuna Expressway Industrial Development Authority (YEIDA)',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Jewar',
    mauza: 'Ranhera',
    khasraNumbers: ['55/1', '55/2', '56/3', '58/1'],
    stage: 'STAGE_7_RR_AWARD_DISBURSEMENT',
    stageNumber: 7,
    totalAreaHectares: 122.4,
    affectedFamiliesCount: 310,
    totalEstimatedCompensation: 890000000,
    disbursedCompensation: 650000000,
    dateInitiated: '2025-01-10',
    lastUpdated: '2026-08-15',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 23-31 Rehabilitation & Resettlement Award',
    parcels: [
      { khasraNumber: '55/1', mauza: 'Ranhera', soilType: 'Multi-cropped Agricultural', areaHectares: 45.0, ownerName: 'Kishan Lal & Brothers', circleRatePerSqMtr: 2100, solatiumMultiplier: 2.0 },
      { khasraNumber: '55/2', mauza: 'Ranhera', soilType: 'Multi-cropped Agricultural', areaHectares: 38.4, ownerName: 'Dharmendra Singh', circleRatePerSqMtr: 2100, solatiumMultiplier: 2.0 },
      { khasraNumber: '56/3', mauza: 'Ranhera', soilType: 'Abadi / Habitation', areaHectares: 19.0, ownerName: 'Gram Samaj Jewar', circleRatePerSqMtr: 3400, solatiumMultiplier: 2.0 },
      { khasraNumber: '58/1', mauza: 'Ranhera', soilType: 'Agricultural', areaHectares: 20.0, ownerName: 'Rohtash Sharma', circleRatePerSqMtr: 2100, solatiumMultiplier: 2.0 }
    ],
    auditTrail: [
      {
        id: 'aud-006',
        timestamp: '2026-08-15T12:00:00Z',
        actorName: 'Ritu Maheshwari, IAS (Administrator RR)',
        actorRole: 'RR_ADMIN',
        action: 'DISBURSE_COMPENSATION',
        stage: 'STAGE_7_RR_AWARD_DISBURSEMENT',
        details: 'DBT tranche of ₹65 Cr released directly into Aadhaar-seeded accounts of 220 landowning families.',
        sha256Hash: 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d'
      }
    ]
  },
  {
    id: 'case-004',
    caseNumber: 'UK-PAURI-2026-00301',
    projectTitle: 'Chamba–Dharasu Tunnel Approach Road (Char Dham National Highway Widening)',
    projectPurpose: 'Strategic hill-corridor connectivity and bypass construction for heavy military & public transport',
    requiringDepartment: 'Rail Vikas Nigam Limited (RVNL)',
    state: 'Uttarakhand',
    district: 'Pauri Garhwal',
    tehsil: 'Chamba',
    mauza: 'Dharasu',
    khasraNumbers: ['210/1-A', '210/2', '214/5'],
    stage: 'returned_for_clarification',
    stageNumber: 1,
    totalAreaHectares: 14.8,
    affectedFamiliesCount: 38,
    totalEstimatedCompensation: 84000000,
    disbursedCompensation: 0,
    dateInitiated: '2026-07-10',
    lastUpdated: '2026-09-02',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 4(1) Requisition Scrutiny',
    parcels: [
      { khasraNumber: '210/1-A', mauza: 'Dharasu', soilType: 'Terraced Agricultural', areaHectares: 6.2, ownerName: 'Bhagat Singh Panwar', circleRatePerSqMtr: 1200, solatiumMultiplier: 2.0 },
      { khasraNumber: '210/2', mauza: 'Dharasu', soilType: 'Non-irrigated (Upraon)', areaHectares: 4.8, ownerName: 'Shyam Lal Semwal', circleRatePerSqMtr: 980, solatiumMultiplier: 2.0 },
      { khasraNumber: '214/5', mauza: 'Dharasu', soilType: 'Rocky Forest Outcrop', areaHectares: 3.8, ownerName: 'Van Panchayat Dharasu', circleRatePerSqMtr: 620, solatiumMultiplier: 2.0 }
    ],
    auditTrail: [
      {
        id: 'aud-007',
        timestamp: '2026-07-10T09:00:00Z',
        actorName: 'Deepak Sharma, CPM (RVNL)',
        actorRole: 'REQUIRING_BODY',
        action: 'SUBMIT_PROPOSAL',
        stage: 'proposal_submitted',
        details: 'Submitted Form-1 proposal for tunnel approach alignment.',
        sha256Hash: 'a1b2c3d4e5f60718293a4b5c6d7e8f90123456789abcdef0123456789abcdef0'
      },
      {
        id: 'aud-008',
        timestamp: '2026-09-02T14:30:00Z',
        actorName: 'Ashish Joshi, IAS (District Collector)',
        actorRole: 'COLLECTOR',
        action: 'REQUEST_CLARIFICATION',
        stage: 'returned_for_clarification',
        details: 'Collector Note: Khasra boundaries for parcel 210/1-A in Mauza Dharasu require reconciliation with Tehsil Shajra cadastral map before Section 11 gazette publication.',
        justificationReason: 'Mauza Shajra boundary discrepancy on slope contours',
        sha256Hash: 'b2c3d4e5f6a10718293a4b5c6d7e8f90123456789abcdef0123456789abcdef1'
      }
    ]
  },
  {
    id: 'case-005',
    caseNumber: 'UK-PAURI-2026-00412',
    projectTitle: 'Alaknanda Riverbank Electric Substation & Transmission Grid Feeder',
    projectPurpose: 'Substation land acquisition for electrification of mountain rail corridors',
    requiringDepartment: 'Rail Vikas Nigam Limited (RVNL)',
    state: 'Uttarakhand',
    district: 'Pauri Garhwal',
    tehsil: 'Srinagar',
    mauza: 'Kirtinagar',
    khasraNumbers: ['301/2', '302/1-B'],
    stage: 'proposal_submitted',
    stageNumber: 1,
    totalAreaHectares: 8.5,
    affectedFamiliesCount: 19,
    totalEstimatedCompensation: 42500000,
    disbursedCompensation: 0,
    dateInitiated: '2026-08-25',
    lastUpdated: '2026-08-25',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 4 Requisition Form-1',
    parcels: [
      { khasraNumber: '301/2', mauza: 'Kirtinagar', soilType: 'Riverine Sandy Loam', areaHectares: 4.5, ownerName: 'Manohar Singh Rawat', circleRatePerSqMtr: 1100, solatiumMultiplier: 2.0 },
      { khasraNumber: '302/1-B', mauza: 'Kirtinagar', soilType: 'Riverine Sandy Loam', areaHectares: 4.0, ownerName: 'Gram Sabha Kirtinagar', circleRatePerSqMtr: 750, solatiumMultiplier: 2.0 }
    ],
    auditTrail: [
      {
        id: 'aud-009',
        timestamp: '2026-08-25T11:20:00Z',
        actorName: 'Deepak Sharma, CPM (RVNL)',
        actorRole: 'REQUIRING_BODY',
        action: 'SUBMIT_PROPOSAL',
        stage: 'proposal_submitted',
        details: 'Initial Form-1 requisition submitted for electrical feeder.',
        sha256Hash: 'c3d4e5f6a1b20718293a4b5c6d7e8f90123456789abcdef0123456789abcdef2'
      }
    ]
  },
  {
    id: 'la-2025-0214',
    caseNumber: 'LA-2025-0214',
    projectTitle: 'Peripheral Ring Road',
    projectPurpose: 'Outer peripheral multi-lane arterial connectivity for regional logistics bypass',
    requiringDepartment: 'National Highways Authority of India (NHAI)',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Dadri',
    mauza: 'Tilpata',
    khasraNumbers: ['120/1', '122/4', '125/2'],
    stage: 'proposal_submitted',
    stageNumber: 1,
    totalAreaHectares: 28.5,
    affectedFamiliesCount: 64,
    totalEstimatedCompensation: 195000000,
    disbursedCompensation: 0,
    dateInitiated: '2026-08-31',
    lastUpdated: '2026-09-01',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 4 Requisition Scrutiny',
    parcels: [
      { khasraNumber: '120/1', mauza: 'Tilpata', soilType: 'Agricultural Irrigated', areaHectares: 12.0, ownerName: 'Om Prakash Sharma', circleRatePerSqMtr: 2800, solatiumMultiplier: 2.0 },
      { khasraNumber: '122/4', mauza: 'Tilpata', soilType: 'Agri-Commercial', areaHectares: 9.5, ownerName: 'Virendra Singh', circleRatePerSqMtr: 3200, solatiumMultiplier: 2.0 },
      { khasraNumber: '125/2', mauza: 'Tilpata', soilType: 'Pasture', areaHectares: 7.0, ownerName: 'Gram Sabha Tilpata', circleRatePerSqMtr: 1500, solatiumMultiplier: 2.0 }
    ],
    auditTrail: [
      {
        id: 'aud-gbn-01',
        timestamp: '2026-09-01T10:00:00Z',
        actorName: 'NHAI Project Director',
        actorRole: 'REQUIRING_BODY',
        action: 'SUBMIT_PROPOSAL',
        stage: 'proposal_submitted',
        details: 'Submitted Form-1 proposal for Peripheral Ring Road section.',
        sha256Hash: 'd1e2f3a4b5c60718293a4b5c6d7e8f90123456789abcdef0123456789abcdef3'
      }
    ]
  },
  {
    id: 'la-2025-0187',
    caseNumber: 'LA-2025-0187',
    projectTitle: 'Film City Development',
    projectPurpose: 'State infrastructure development for world-class media and cinematic production hub',
    requiringDepartment: 'Yamuna Expressway Industrial Development Authority (YEIDA)',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Jewar',
    mauza: 'Sector 21',
    khasraNumbers: ['44/1', '45/2-A', '48/3'],
    stage: 'sia_complete',
    stageNumber: 3,
    totalAreaHectares: 65.0,
    affectedFamiliesCount: 112,
    totalEstimatedCompensation: 450000000,
    disbursedCompensation: 0,
    dateInitiated: '2026-07-15',
    lastUpdated: '2026-09-03',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 11(1) Preliminary Gazette Due',
    parcels: [
      { khasraNumber: '44/1', mauza: 'Sector 21', soilType: 'Agricultural', areaHectares: 25.0, ownerName: 'Hargovind Bhati', circleRatePerSqMtr: 2400, solatiumMultiplier: 2.0 },
      { khasraNumber: '45/2-A', mauza: 'Sector 21', soilType: 'Agricultural', areaHectares: 22.0, ownerName: 'Maheshwari Trust', circleRatePerSqMtr: 2400, solatiumMultiplier: 2.0 },
      { khasraNumber: '48/3', mauza: 'Sector 21', soilType: 'Barren Outcrop', areaHectares: 18.0, ownerName: 'Gram Samaj Jewar', circleRatePerSqMtr: 1200, solatiumMultiplier: 2.0 }
    ],
    auditTrail: [
      {
        id: 'aud-gbn-02',
        timestamp: '2026-09-03T11:30:00Z',
        actorName: 'Expert SIA Committee',
        actorRole: 'SIA_EXPERT',
        action: 'SUBMIT_SIA_VERDICT',
        stage: 'sia_complete',
        details: 'SIA report approved with positive public recommendation. Ready for Section 11 gazette.',
        sha256Hash: 'e2f3a4b5c6d10718293a4b5c6d7e8f90123456789abcdef0123456789abcdef4'
      }
    ]
  },
  {
    id: 'la-2025-0179',
    caseNumber: 'LA-2025-0179',
    projectTitle: 'Noida International University',
    projectPurpose: 'State University academic campus and research facility expansion',
    requiringDepartment: 'Higher Education Department, Govt of UP',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Greater Noida',
    mauza: 'Knowledge Park V',
    khasraNumbers: ['78/1', '79/3', '81/2'],
    stage: 'objections_window',
    stageNumber: 5,
    totalAreaHectares: 22.4,
    affectedFamiliesCount: 45,
    totalEstimatedCompensation: 180000000,
    disbursedCompensation: 0,
    dateInitiated: '2026-06-01',
    lastUpdated: '2026-08-26',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 15 Hearing Completed, Award Pending',
    parcels: [
      { khasraNumber: '78/1', mauza: 'Knowledge Park V', soilType: 'Urban Semi-Commercial', areaHectares: 10.0, ownerName: 'Choudhary Braham Singh', circleRatePerSqMtr: 4100, solatiumMultiplier: 2.0 },
      { khasraNumber: '79/3', mauza: 'Knowledge Park V', soilType: 'Agricultural', areaHectares: 8.0, ownerName: 'Suresh Chandra Nagar', circleRatePerSqMtr: 3100, solatiumMultiplier: 2.0 },
      { khasraNumber: '81/2', mauza: 'Knowledge Park V', soilType: 'Habitation Buffer', areaHectares: 4.4, ownerName: 'Panchayat Land', circleRatePerSqMtr: 1800, solatiumMultiplier: 2.0 }
    ],
    auditTrail: [
      {
        id: 'aud-gbn-03',
        timestamp: '2026-08-26T15:45:00Z',
        actorName: 'Priya Singh, IAS (District Collector)',
        actorRole: 'COLLECTOR',
        action: 'RESOLVE_OBJECTION',
        stage: 'objections_window',
        details: 'Section 15 objection hearings completed. Ready to proceed to final compensation award formulation.',
        sha256Hash: 'f3a4b5c6d1e20718293a4b5c6d7e8f90123456789abcdef0123456789abcdef5'
      }
    ]
  },
  {
    id: 'la-2025-0168',
    caseNumber: 'LA-2025-0168',
    projectTitle: 'Logistics Park (Phase 2)',
    projectPurpose: 'Multi-modal freight consolidation and warehousing zone near Western DFC',
    requiringDepartment: 'Dedicated Freight Corridor Corporation of India (DFCCIL)',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Dadri',
    mauza: 'Chhapraula',
    khasraNumbers: ['215/1', '216/4'],
    stage: 'compensation_disbursed',
    stageNumber: 7,
    totalAreaHectares: 38.0,
    affectedFamiliesCount: 94,
    totalEstimatedCompensation: 285000000,
    disbursedCompensation: 285000000,
    dateInitiated: '2025-11-20',
    lastUpdated: '2026-08-30',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 38 Possession Confirmation Due',
    parcels: [
      { khasraNumber: '215/1', mauza: 'Chhapraula', soilType: 'Industrial Sub-zone', areaHectares: 20.0, ownerName: 'Kailash Chand & Sons', circleRatePerSqMtr: 3800, solatiumMultiplier: 2.0 },
      { khasraNumber: '216/4', mauza: 'Chhapraula', soilType: 'Industrial Sub-zone', areaHectares: 18.0, ownerName: 'Gautam Agro Hub', circleRatePerSqMtr: 3800, solatiumMultiplier: 2.0 }
    ],
    auditTrail: [
      {
        id: 'aud-gbn-04',
        timestamp: '2026-08-30T17:00:00Z',
        actorName: 'RR Directorate',
        actorRole: 'RR_ADMIN',
        action: 'DISBURSE_COMPENSATION',
        stage: 'compensation_disbursed',
        details: '100% DBT solatium disbursed into beneficiary bank accounts. Awaiting joint possession confirmation with Field Officer.',
        sha256Hash: 'a4b5c6d1e2f30718293a4b5c6d7e8f90123456789abcdef0123456789abcdef6'
      }
    ]
  },
  {
    id: 'la-2025-0156',
    caseNumber: 'LA-2025-0156',
    projectTitle: 'Data Centre Park',
    projectPurpose: 'Hyperscale cloud datacenter infrastructure development',
    requiringDepartment: 'UP Electronics Corporation Limited (UPECL)',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Greater Noida',
    mauza: 'Sector TechZone IV',
    khasraNumbers: ['50/1', '52/2'],
    stage: 'state_review',
    stageNumber: 2,
    totalAreaHectares: 15.0,
    affectedFamiliesCount: 18,
    totalEstimatedCompensation: 120000000,
    disbursedCompensation: 0,
    dateInitiated: '2026-05-10',
    lastUpdated: '2026-08-19',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • State Secretariat Sanction Review',
    parcels: [],
    auditTrail: []
  },
  {
    id: 'la-2025-0143',
    caseNumber: 'LA-2025-0143',
    projectTitle: 'Metro Corridor Extension',
    projectPurpose: 'Aqua Line extension to Greater Noida West Sector 12',
    requiringDepartment: 'Noida Metro Rail Corporation (NMRC)',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Dadri',
    mauza: 'Bhangel',
    khasraNumbers: ['88/2', '91/1'],
    stage: 'award_issued',
    stageNumber: 6,
    totalAreaHectares: 12.5,
    affectedFamiliesCount: 32,
    totalEstimatedCompensation: 98000000,
    disbursedCompensation: 45000000,
    dateInitiated: '2025-10-04',
    lastUpdated: '2026-08-15',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 23 Award Declared',
    parcels: [],
    auditTrail: []
  },
  {
    id: 'la-2025-0128',
    caseNumber: 'LA-2025-0128',
    projectTitle: 'Integrated Township',
    projectPurpose: 'Affordable residential and commercial greenfield urban township',
    requiringDepartment: 'New Okhla Industrial Development Authority (NOIDA)',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Noida',
    mauza: 'Mamura',
    khasraNumbers: ['14/1', '15/2', '16/3'],
    stage: 'rr_in_progress',
    stageNumber: 7,
    totalAreaHectares: 45.0,
    affectedFamiliesCount: 140,
    rrFamiliesTotal: 10,
    rrFamiliesVerified: 6,
    totalEstimatedCompensation: 380000000,
    disbursedCompensation: 180000000,
    dateInitiated: '2025-04-12',
    lastUpdated: '2026-08-01',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • R&R Scheme Formulation',
    parcels: [],
    auditTrail: []
  },
  {
    id: 'la-2025-0111',
    caseNumber: 'LA-2025-0111',
    projectTitle: 'Skill Development Institute',
    projectPurpose: 'National skill training center and polytechnic facility',
    requiringDepartment: 'National Skill Development Corporation (NSDC)',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Jewar',
    mauza: 'Dayanatpur',
    khasraNumbers: ['9/1', '10/2'],
    stage: 'possession_taken',
    stageNumber: 8,
    totalAreaHectares: 8.0,
    affectedFamiliesCount: 12,
    totalEstimatedCompensation: 56000000,
    disbursedCompensation: 56000000,
    dateInitiated: '2025-02-18',
    lastUpdated: '2026-07-27',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 38 Possession Handover Complete',
    parcels: [],
    auditTrail: []
  },
  // Additional Action Cases (4) to reach exactly 8 action cases for Gautam Buddha Nagar
  {
    id: 'la-2025-0222',
    caseNumber: 'LA-2025-0222',
    projectTitle: 'Yamuna Expressway Interchange Spur',
    projectPurpose: 'Dedicated grade-separated cloverleaf interchange connecting Sector 29 industrial corridor',
    requiringDepartment: 'Yamuna Expressway Industrial Development Authority (YEIDA)',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Jewar',
    mauza: 'Dungarpur Rilka',
    khasraNumbers: ['18/2', '19/1'],
    stage: 'proposal_submitted',
    stageNumber: 1,
    totalAreaHectares: 16.2,
    affectedFamiliesCount: 36,
    totalEstimatedCompensation: 115000000,
    disbursedCompensation: 0,
    dateInitiated: '2026-08-28',
    lastUpdated: '2026-09-02',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 4 Requisition Form-1 Review',
    parcels: [],
    auditTrail: []
  },
  {
    id: 'la-2025-0205',
    caseNumber: 'LA-2025-0205',
    projectTitle: 'Eco-Tech VI Industrial Zone',
    projectPurpose: 'Electronics manufacturing and green energy component assembly zone',
    requiringDepartment: 'Greater Noida Industrial Development Authority (GNIDA)',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Greater Noida',
    mauza: 'Pali',
    khasraNumbers: ['102/1', '105/3'],
    stage: 'sia_complete',
    stageNumber: 3,
    totalAreaHectares: 42.0,
    affectedFamiliesCount: 88,
    totalEstimatedCompensation: 310000000,
    disbursedCompensation: 0,
    dateInitiated: '2026-06-18',
    lastUpdated: '2026-08-29',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 11 Preliminary Notification Due',
    parcels: [],
    auditTrail: []
  },
  {
    id: 'la-2025-0191',
    caseNumber: 'LA-2025-0191',
    projectTitle: 'Jewar Airport Eastern Rail Link',
    projectPurpose: 'Broad-gauge dedicated freight and passenger connection to Chola railway junction',
    requiringDepartment: 'Northern Railway',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Jewar',
    mauza: 'Kishorepur',
    khasraNumbers: ['61/2', '62/4', '65/1'],
    stage: 'objections_window',
    stageNumber: 5,
    totalAreaHectares: 31.5,
    affectedFamiliesCount: 72,
    totalEstimatedCompensation: 240000000,
    disbursedCompensation: 0,
    dateInitiated: '2026-05-22',
    lastUpdated: '2026-08-20',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 15 Hearing Concluded',
    parcels: [],
    auditTrail: []
  },
  {
    id: 'la-2025-0174',
    caseNumber: 'LA-2025-0174',
    projectTitle: 'Greater Noida Power Transmission Hub',
    projectPurpose: '400/220 kV Gas Insulated Substation to support data center cluster',
    requiringDepartment: 'UP Power Transmission Corporation Limited (UPPTCL)',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Dadri',
    mauza: 'Ghori',
    khasraNumbers: ['141/1', '142/2'],
    stage: 'compensation_disbursed',
    stageNumber: 7,
    totalAreaHectares: 19.4,
    affectedFamiliesCount: 44,
    totalEstimatedCompensation: 165000000,
    disbursedCompensation: 165000000,
    dateInitiated: '2025-12-08',
    lastUpdated: '2026-08-25',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 38 Possession Handover Stage',
    parcels: [],
    auditTrail: []
  },
  // Additional District Overview Cases (11) to reach total 24 district cases
  {
    id: 'la-2025-0105',
    caseNumber: 'LA-2025-0105',
    projectTitle: 'Sector 150 Sports City Green Buffer',
    projectPurpose: 'Riverfront ecological reserve and flood protection bund embankment',
    requiringDepartment: 'NOIDA Authority',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Noida',
    mauza: 'Garhi Samastpur',
    khasraNumbers: ['22/1'],
    stage: 'state_review',
    stageNumber: 2,
    totalAreaHectares: 11.2,
    affectedFamiliesCount: 15,
    totalEstimatedCompensation: 92000000,
    disbursedCompensation: 0,
    dateInitiated: '2026-04-14',
    lastUpdated: '2026-08-12',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • State Screening',
    parcels: [],
    auditTrail: []
  },
  {
    id: 'la-2025-0098',
    caseNumber: 'LA-2025-0098',
    projectTitle: 'Surajpur Wetland Eco-Tourism Buffer',
    projectPurpose: 'Conservation boundary protection and nature interpretation corridor',
    requiringDepartment: 'UP Forest & Wildlife Department',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Dadri',
    mauza: 'Surajpur',
    khasraNumbers: ['89/3'],
    stage: 'state_review',
    stageNumber: 2,
    totalAreaHectares: 14.0,
    affectedFamiliesCount: 8,
    totalEstimatedCompensation: 78000000,
    disbursedCompensation: 0,
    dateInitiated: '2026-03-10',
    lastUpdated: '2026-08-08',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • State Sanction',
    parcels: [],
    auditTrail: []
  },
  {
    id: 'la-2025-0091',
    caseNumber: 'LA-2025-0091',
    projectTitle: 'Western Dedicated Freight Corridor Dadri Yard',
    projectPurpose: 'Container transshipment hub and rolling stock maintenance depot',
    requiringDepartment: 'DFCCIL',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Dadri',
    mauza: 'Dhoom Manikpur',
    khasraNumbers: ['310/1', '312/4'],
    stage: 'award_issued',
    stageNumber: 6,
    totalAreaHectares: 33.6,
    affectedFamiliesCount: 68,
    totalEstimatedCompensation: 290000000,
    disbursedCompensation: 140000000,
    dateInitiated: '2025-08-11',
    lastUpdated: '2026-07-29',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 23 Award Finalized',
    parcels: [],
    auditTrail: []
  },
  {
    id: 'la-2025-0084',
    caseNumber: 'LA-2025-0084',
    projectTitle: 'Noida-Greater Noida Expressway Flyover Expansion',
    projectPurpose: 'Congestion relief loops at Advant Navis intersection',
    requiringDepartment: 'NOIDA Authority',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Noida',
    mauza: 'Wajidpur',
    khasraNumbers: ['45/1'],
    stage: 'award_issued',
    stageNumber: 6,
    totalAreaHectares: 6.8,
    affectedFamiliesCount: 14,
    totalEstimatedCompensation: 62000000,
    disbursedCompensation: 30000000,
    dateInitiated: '2025-07-05',
    lastUpdated: '2026-07-21',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 23 Award Declared',
    parcels: [],
    auditTrail: []
  },
  {
    id: 'la-2025-0077',
    caseNumber: 'LA-2025-0077',
    projectTitle: 'Bhangel Elevated Road Slip Roads',
    projectPurpose: 'At-grade entry/exit ramps and service lane integration',
    requiringDepartment: 'UP Public Works Department (PWD)',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Dadri',
    mauza: 'Salarpur',
    khasraNumbers: ['112/1'],
    stage: 'rr_in_progress',
    stageNumber: 7,
    totalAreaHectares: 8.5,
    affectedFamiliesCount: 29,
    totalEstimatedCompensation: 74000000,
    disbursedCompensation: 35000000,
    dateInitiated: '2025-06-19',
    lastUpdated: '2026-07-15',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • R&R Execution',
    parcels: [],
    auditTrail: []
  },
  {
    id: 'la-2025-0069',
    caseNumber: 'LA-2025-0069',
    projectTitle: 'Jewar Multi-Modal Cargo Terminal Access Road',
    projectPurpose: 'Heavy logistics 4-lane link to State Highway 22A',
    requiringDepartment: 'YEIDA',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Jewar',
    mauza: 'Rohi',
    khasraNumbers: ['204/1', '205/3'],
    stage: 'rr_in_progress',
    stageNumber: 7,
    totalAreaHectares: 26.0,
    affectedFamiliesCount: 70,
    totalEstimatedCompensation: 215000000,
    disbursedCompensation: 110000000,
    dateInitiated: '2025-05-14',
    lastUpdated: '2026-07-02',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Solatium Tranche 2',
    parcels: [],
    auditTrail: []
  },
  {
    id: 'la-2025-0058',
    caseNumber: 'LA-2025-0058',
    projectTitle: 'Chipyana Buzurg Railway Overbridge (ROB)',
    projectPurpose: 'Level crossing elimination on Delhi–Howrah mainline',
    requiringDepartment: 'Northern Railway',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Dadri',
    mauza: 'Chipyana Buzurg',
    khasraNumbers: ['51/1'],
    stage: 'possession_taken',
    stageNumber: 8,
    totalAreaHectares: 4.2,
    affectedFamiliesCount: 11,
    totalEstimatedCompensation: 38000000,
    disbursedCompensation: 38000000,
    dateInitiated: '2025-01-20',
    lastUpdated: '2026-06-25',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 38 Completed',
    parcels: [],
    auditTrail: []
  },
  {
    id: 'la-2025-0044',
    caseNumber: 'LA-2025-0044',
    projectTitle: 'Sector 145 Sewerage Treatment Plant Expansion',
    projectPurpose: '100 MLD advanced tertiary treatment facility for Noida South',
    requiringDepartment: 'NOIDA Water & Sewage Wing',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Noida',
    mauza: 'Nalgadha',
    khasraNumbers: ['82/2', '83/1'],
    stage: 'possession_taken',
    stageNumber: 8,
    totalAreaHectares: 9.8,
    affectedFamiliesCount: 18,
    totalEstimatedCompensation: 88000000,
    disbursedCompensation: 88000000,
    dateInitiated: '2024-11-15',
    lastUpdated: '2026-05-30',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Possession Complete',
    parcels: [],
    auditTrail: []
  },
  {
    id: 'la-2025-0033',
    caseNumber: 'LA-2025-0033',
    projectTitle: 'Pari Chowk Underpass & Drainage Diversion',
    projectPurpose: 'Stormwater management culverts and grade-separated underpass',
    requiringDepartment: 'GNIDA',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Greater Noida',
    mauza: 'Tugalpur',
    khasraNumbers: ['15/1'],
    stage: 'possession_taken',
    stageNumber: 8,
    totalAreaHectares: 5.5,
    affectedFamiliesCount: 9,
    totalEstimatedCompensation: 49000000,
    disbursedCompensation: 49000000,
    dateInitiated: '2024-10-02',
    lastUpdated: '2026-05-18',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 38 Transferred',
    parcels: [],
    auditTrail: []
  },
  {
    id: 'la-2025-0021',
    caseNumber: 'LA-2025-0021',
    projectTitle: 'Kasna District Hospital Emergency Trauma Center',
    projectPurpose: '200-bed trauma hospital and helipad facility',
    requiringDepartment: 'Department of Medical Health & Family Welfare, UP',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Greater Noida',
    mauza: 'Kasna',
    khasraNumbers: ['178/1', '179/2'],
    stage: 'possession_taken',
    stageNumber: 8,
    totalAreaHectares: 12.0,
    affectedFamiliesCount: 22,
    totalEstimatedCompensation: 105000000,
    disbursedCompensation: 105000000,
    dateInitiated: '2024-08-14',
    lastUpdated: '2026-04-10',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Handover Completed',
    parcels: [],
    auditTrail: []
  },
  {
    id: 'la-2025-0010',
    caseNumber: 'LA-2025-0010',
    projectTitle: 'Eastern Peripheral Expressway Freight Toll Plaza',
    projectPurpose: 'Automated barrierless toll plaza and weigh-in-motion bay',
    requiringDepartment: 'NHAI',
    state: 'Uttar Pradesh',
    district: 'Gautam Buddha Nagar',
    tehsil: 'Dadri',
    mauza: 'Beel Akbarpur',
    khasraNumbers: ['240/1'],
    stage: 'possession_taken',
    stageNumber: 8,
    totalAreaHectares: 7.2,
    affectedFamiliesCount: 16,
    totalEstimatedCompensation: 68000000,
    disbursedCompensation: 68000000,
    dateInitiated: '2024-06-05',
    lastUpdated: '2026-03-15',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 38 Sealed',
    parcels: [],
    auditTrail: []
  },
  // Dedicated SIA Expert Assigned Cases (Prompt 5)
  {
    id: 'sia-case-01',
    caseNumber: 'UK-PAURI-2026-00501',
    projectTitle: 'Rishikesh–Devprayag Rail Tunnel Section 4',
    projectPurpose: 'Mountain railway double-line tunnel construction and access portals',
    requiringDepartment: 'Rail Vikas Nigam Limited (RVNL)',
    state: 'Uttarakhand',
    district: 'Pauri Garhwal',
    tehsil: 'Devprayag',
    mauza: 'Kaudiyala',
    khasraNumbers: ['14/1', '15/2'],
    stage: 'sia_in_progress',
    stageNumber: 3,
    totalAreaHectares: 12.8,
    affectedFamiliesCount: 28,
    totalEstimatedCompensation: 98000000,
    disbursedCompensation: 0,
    dateInitiated: '2026-08-15',
    lastUpdated: '2026-09-02',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 4 SIA Study Commissioned',
    assignedTo: 'user-004',
    hearingLogged: false,
    parcels: [],
    auditTrail: []
  },
  {
    id: 'sia-case-02',
    caseNumber: 'UK-TEHRI-2026-00502',
    projectTitle: 'Tehri Catchment Solar Energy Substation',
    projectPurpose: 'Green energy evacuation terminal and high-voltage transmission substation',
    requiringDepartment: 'Uttarakhand Power Corporation Limited (UPCL)',
    state: 'Uttarakhand',
    district: 'Tehri Garhwal',
    tehsil: 'Narendra Nagar',
    mauza: 'Chamba',
    khasraNumbers: ['88/2', '89/1'],
    stage: 'sia_in_progress',
    stageNumber: 3,
    totalAreaHectares: 18.5,
    affectedFamiliesCount: 42,
    totalEstimatedCompensation: 135000000,
    disbursedCompensation: 0,
    dateInitiated: '2026-08-01',
    lastUpdated: '2026-09-04',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 7 SIA Public Hearing Concluded',
    assignedTo: 'user-004',
    hearingLogged: true,
    parcels: [],
    auditTrail: []
  },
  // Dedicated Field Officer Tasks (Prompt 7)
  {
    id: 'fo-case-01',
    caseNumber: 'UK-PAURI-2026-00601',
    projectTitle: 'Srinagar Bypass Elevated Flyover Cadastral Survey',
    projectPurpose: 'Ground-truthing and physical inventory of trees and built structures on Khasra 312',
    requiringDepartment: 'National Highways & Infrastructure Development Corporation (NHIDCL)',
    state: 'Uttarakhand',
    district: 'Pauri Garhwal',
    tehsil: 'Srinagar',
    mauza: 'Rampur',
    khasraNumbers: ['312/1', '312/2'],
    stage: 'STAGE_1_PROPOSAL_PENDING',
    stageNumber: 1,
    totalAreaHectares: 6.4,
    affectedFamiliesCount: 14,
    totalEstimatedCompensation: 42000000,
    disbursedCompensation: 0,
    dateInitiated: '2026-08-20',
    lastUpdated: '2026-09-03',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Field Inspection Requisition',
    assignedFieldOfficerId: 'user-006',
    verificationTaskPending: true,
    parcels: [],
    auditTrail: []
  },
  {
    id: 'fo-case-02',
    caseNumber: 'UK-PAURI-2026-00602',
    projectTitle: 'Koteshwar Dam Left Bank Realignment (Possession)',
    projectPurpose: 'Hydroelectric reservoir slope protection and safety buffer zone',
    requiringDepartment: 'THDC India Limited',
    state: 'Uttarakhand',
    district: 'Pauri Garhwal',
    tehsil: 'Kirtinagar',
    mauza: 'Maletha',
    khasraNumbers: ['410/1', '412/3'],
    stage: 'compensation_disbursed',
    stageNumber: 7,
    totalAreaHectares: 15.0,
    affectedFamiliesCount: 31,
    totalEstimatedCompensation: 110000000,
    disbursedCompensation: 110000000,
    dateInitiated: '2025-09-10',
    lastUpdated: '2026-09-01',
    isUrgentSec40: false,
    rfctlarrActCitation: 'RFCTLARR Act, 2013 • Section 38 Joint Possession Handover',
    assignedFieldOfficerId: 'user-006',
    parcels: [],
    auditTrail: []
  }
];
